name: Create Pull Request

on:
  workflow_call:
    secrets:
      token:
        description: GitHub token
        required: true
    inputs:
      token:
        type: string
        description: GitHub token
        required: true
      base-branch:
        type: string
        description: Base branch to checkout from and merge into
        required: true
      checkout-branch:
        type: string
        description: Checked out branch to create PR from
        required: true
      commit-message:
        type: string
        description: 'Commit message'
        required: true
      title:
        type: string
        description: Pull Request title
        required: true
      body:
        type: string
        description: Pull Request body
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ inputs.token || secrets.token }}
          base: ${{ inputs.base-branch }}
          branch: ${{ inputs.checkout-branch }}
          commit-message: ${{ inputs.commit-message }}
          title: ${{ inputs.title }}
          body: ${{ inputs.body }}
