name: Pull Request Self-Assignment

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to its author
        uses: toshimaru/auto-author-assign@4d585cc37690897bd9015942ed6e766aa7cdb97f # v3.0.1
