name: Checkout Branch

on:
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
